elixir:
  - changed-files:
      - any-glob-to-any-file:
          - .github/elixir-test-matrix.json
          - instrumentation/**/*.ex
          - instrumentation/**/*.exs
          - instrumentation/**/mix.lock
          - propagators/**/*.ex
          - propagators/**/*.exs
          - propagators/**/mix.lock
          - exporters/**/*.ex
          - exporters/**/*.exs
          - exporters/**/mix.lock
          - examples/**/*.ex
          - examples/**/*.exs
          - examples/**/mix.lock
          - utilities/**/*.ex
          - utilities/**/*.exs
          - utilities/**/mix.lock

erlang:
  - changed-files:
      - any-glob-to-any-file:
          - .github/erlang-test-matrix.json
          - instrumentation/**/*.erl
          - instrumentation/**/*.hrl
          - instrumentation/**/rebar.*
          - propagators/**/*.erl
          - propagators/**/*.hrl
          - propagators/**/rebar.*
          - exporters/**/*.erl
          - exporters/**/*.hrl
          - exporters/**/rebar.*
          - examples/**/*.erl
          - examples/**/*.hrl
          - examples/**/rebar.*
          - utilities/**/*.erl
          - utilities/**/*.hrl
          - utilities/**/rebar.*

instrumentation:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/**/*

propagators:
  - changed-files:
      - any-glob-to-any-file:
          - propagators/**/*

examples:
  - changed-files:
      - any-glob-to-any-file:
          - examples/**/*

utilities:
  - changed-files:
      - any-glob-to-any-file:
          - utilities/**/*

scope-ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**

opentelemetry_aws_xray:
  - changed-files:
      - any-glob-to-any-file:
          - utilities/opentelemetry_aws_xray/**/*

opentelemetry_broadway:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_broadway/**/*

opentelemetry_cowboy:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_cowboy/**/*

opentelemetry_dataloader:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_dataloader/**/*

opentelemetry_ecto:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_ecto/**/*

opentelemetry_elli:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_elli/**/*

opentelemetry_finch:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_finch/**/*

opentelemetry_grpcbox:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_grpcbox/**/*

opentelemetry_httpoison:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_httpoison/**/*

opentelemetry_nebulex:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_nebulex/**/*

opentelemetry_oban:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_oban/**/*

opentelemetry_phoenix:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_phoenix/**/*

opentelemetry_bandit:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_bandit/**/*

opentelemetry_process_propagator:
  - changed-files:
      - any-glob-to-any-file:
          - propagators/opentelemetry_process_propagator/**/*

opentelemetry_redix:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_redix/**/*

opentelemetry_req:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_req/**/*

opentelemetry_telemetry:
  - changed-files:
      - any-glob-to-any-file:
          - utilities/opentelemetry_telemetry/**/*

opentelemetry_tesla:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_tesla/**/*

opentelemetry_xandra:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_xandra/**/*

opentelemetry_commanded:
  - changed-files:
      - any-glob-to-any-file:
          - instrumentation/opentelemetry_commanded/**/*

otel_http:
  - changed-files:
      - any-glob-to-any-file:
          - utilities/otel_http/**/*
