_extends: opentelemetry-erlang-contrib:.github/release-drafter.yml
name-template: 'Opentelemetry Finch - v$RESOLVED_VERSION'
tag-template: 'opentelemetry-finch-v$RESOLVED_VERSION'
tag-prefix: opentelemetry-finch-v
include-paths:
  - instrumentation/opentelemetry_finch/
