_extends: opentelemetry-erlang-contrib:.github/release-drafter.yml
name-template: 'Opentelemetry Ecto - v$RESOLVED_VERSION'
tag-template: 'opentelemetry-ecto-v$RESOLVED_VERSION'
tag-prefix: opentelemetry-ecto-v
include-paths:
  - instrumentation/opentelemetry_ecto/
