_extends: opentelemetry-erlang-contrib:.github/release-drafter.yml
name-template: 'Opentelemetry Dataloader - v$RESOLVED_VERSION'
tag-template: 'opentelemetry-dataloader-v$RESOLVED_VERSION'
tag-prefix: opentelemetry-dataloader-v
include-paths:
  - instrumentation/opentelemetry_dataloader/lib/**/*
  - instrumentation/opentelemetry_dataloader/lib/mix.*
