_extends: opentelemetry-erlang-contrib:.github/release-drafter.yml
name-template: 'Opentelemetry Oban - v$RESOLVED_VERSION'
tag-template: 'opentelemetry-oban-v$RESOLVED_VERSION'
tag-prefix: opentelemetry-oban-v
include-paths:
  - instrumentation/opentelemetry_oban/lib/**/*
  - instrumentation/opentelemetry_oban/lib/mix.*
