_extends: opentelemetry-erlang-contrib:.github/release-drafter.yml
name-template: 'Opentelemetry Instrumentation HTTP - v$RESOLVED_VERSION'
tag-template: 'opentelemetry-instrumentation-http-v$RESOLVED_VERSION'
tag-prefix: opentelemetry-instrumentation-http-v
include-paths:
  - utilities/opentelemetry_instrumentation-http/
