_extends: opentelemetry-erlang-contrib:.github/release-drafter.yml
name-template: 'Opentelemetry Telemetry - v$RESOLVED_VERSION'
tag-template: 'opentelemetry-telemetry-v$RESOLVED_VERSION'
tag-prefix: opentelemetry-telemetry-v
include-paths:
  - utilities/opentelemetry_telemetry/
