_extends: opentelemetry-erlang-contrib:.github/release-drafter.yml
name-template: 'Opentelemetry AWS X-Ray - v$RESOLVED_VERSION'
tag-template: 'opentelemetry-aws-xray-v$RESOLVED_VERSION'
tag-prefix: opentelemetry-aws-xray-v
include-paths:
  - utilities/opentelemetry_aws_xray/src/**/*
  - utilities/opentelemetry_aws_xray/rebar.*
