receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:55680"
      http:
        endpoint: "0.0.0.0:55681"
processors:
exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    sending_queue:
      batch:
extensions:
  zpages: {}
service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [zipkin]

