version: '3'
services:
  postgres:
    image: 'postgres:18.6@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_dev

  otel:
    image: otel/opentelemetry-collector-contrib:0.159.0@sha256:1f2c54a30e713fac6b3ae77a1ec84010c2007e29ced8ec666214fc2f6739c1cc
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318"
      - '55681:55681'
      - '55680:55680'
      - "55679:55679"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - jaeger
      - zipkin

  zipkin:
    image: openzipkin/zipkin-slim:3.6.1@sha256:fc29b9862c14f4fc241cf0259c585e1cfd4e9b18f01ad36d86adaabb7d01815c
    container_name: "zipkin"
    ports:
      - '9411:9411'

  # Jaeger
  jaeger:
    image: jaegertracing/jaeger:2.20.0@sha256:46a886260e04002d8f45e213fc39063fa11a50446048fdaa64786fc0840cb9f8
    container_name: "jaeger"
    ports:
      - "4317:4317"
      - "16686:16686"
      - "14268"
      - "14250:14250"
