receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
    send_batch_size: 1024
    timeout: 5s
exporters:
  otlp:
    # Uncomment below for using Honeycomb
    # endpoint: "api.honeycomb.io:443"
    # headers:
    #   "x-honeycomb-team": "<YOUR_ACCESS_TOKEN>"
    #   "x-honeycomb-dataset": "<YOUR_DATASET_NAME>"
    # Uncomment below for using Lightstep
    # endpoint: ingest.lightstep.com:443
    # headers:
    #   "lightstep-access-token": "<YOUR_ACCESS_TOKEN>"
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    tls:
      insecure: true
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
extensions:
  zpages:
    endpoint: :55679
service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, zipkin]
      # Add 'otlp' if you're exporting to Honeycomb
      # or Lightstep
      # exporters: [zipkin, jaeger, otlp]


