version: "3.7"

services:
  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opentelemetry_oban_test
    ports:
      - 5432:5432
